package com.example.einkarcade.ui

internal const val GAME_CONTROL_HEIGHT_DP = 48f
internal const val GAME_TITLE_TOP_PADDING_DP = 8f
internal const val GAME_TITLE_BOTTOM_PADDING_DP = 2f
internal const val GAME_HUD_TOP_PADDING_DP = 2f
internal const val GAME_HUD_BOTTOM_PADDING_DP = 8f

internal const val GAME_BOARD_TOP_UI_RESERVE_DP =
    GAME_CONTROL_HEIGHT_DP + GAME_TITLE_TOP_PADDING_DP + GAME_TITLE_BOTTOM_PADDING_DP
internal const val GAME_BOARD_BOTTOM_UI_RESERVE_DP =
    GAME_CONTROL_HEIGHT_DP + GAME_HUD_TOP_PADDING_DP + GAME_HUD_BOTTOM_PADDING_DP
